create table if not exists public.grape_aliases (
  id bigint generated by default as identity primary key,
  grape_id bigint not null references public.grapes(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create index if not exists grape_aliases_grape_id_idx
  on public.grape_aliases (grape_id);

create unique index if not exists grape_aliases_name_lower_idx
  on public.grape_aliases (lower(name));

alter table public.grape_aliases enable row level security;

drop policy if exists grape_aliases_select on public.grape_aliases;
create policy grape_aliases_select on public.grape_aliases
  for select to authenticated using (true);

drop policy if exists grape_aliases_insert on public.grape_aliases;
create policy grape_aliases_insert on public.grape_aliases
  for insert to authenticated with check (true);

drop policy if exists grape_aliases_update on public.grape_aliases;
create policy grape_aliases_update on public.grape_aliases
  for update to authenticated using (true) with check (true);

drop policy if exists grape_aliases_delete on public.grape_aliases;
create policy grape_aliases_delete on public.grape_aliases
  for delete to authenticated using (true);

alter table public.wine_grapes
  add column if not exists display_name text;

update public.wine_grapes
set display_name = public.grapes.name
from public.grapes
where public.wine_grapes.grape_id = public.grapes.id
  and public.wine_grapes.display_name is null;

alter table public.wine_grapes
  alter column display_name set not null;
